project:
  title: Behaverse
  type: website
  execute-dir: project

execute:
  enabled: false

website:
  navbar:
    left:
      - api/index.qmd

interlinks:
  fast: true
  sources:
    pandas:
      url: https://pandas.pydata.org/docs/

format:
  html:
    theme: cosmo
    toc: true

filters:
  - interlinks

# tell quarto to read the generated sidebar
metadata-files:
  - api/_sidebar.yml

quartodoc:
  package: behaverse
  dir: api
  source_dir: ../src
  parser: 'google'
  title: "API"
  render_interlinks: true

  # # write sidebar data to this file
  sidebar: api/_sidebar.yml

  sections:
  - title: Object-Oriented API
    package: behaverse
    contents:
      - name: Dataset
        children: separate
        members:
          - load_all
          - load
          - describe
          - select
          - validate
      - name: DatasetDescription
        children: separate
  - title: Functional API
    package: behaverse
    contents:
      - list_datasets
      - load_dataset
      - describe_dataset
      - validate_dataset
  - title: Utilities
    package: behaverse.utils
    contents:
      - download_dataset
      - extract_dataset
