
# tell quarto to read the generated sidebar
metadata-files:
  - api/_sidebar.yml

interlinks:
 sources:
    python:
      url: https://docs.python.org/3/

quartodoc:
  package: behaverse
  dir: api
  source_dir: src
  parser: 'google'
  title: "API"

  # # write sidebar data to this file
  sidebar: api/_sidebar.yml

  sections:
  - title: Dataset
    contents:
      - package: behaverse.dataset
        name: Dataset
        children: separate
      - package: behaverse.dataset_info
        name: DatasetInfo
        children: separate