
# tell quarto to read the generated sidebar
metadata-files:
  - api/_sidebar.yml

interlinks:
 sources:
    python:
      url: https://docs.python.org/3/

quartodoc:
  package: behaverse
  dir: api
  source_dir: src
  parser: 'google'
  title: "API"

  # # write sidebar data to this file
  sidebar: api/_sidebar.yml

  sections:
  - title: Object-Oriented API
    package: behaverse
    contents:
      - name: Dataset
        children: separate
        members:
          - download
          - load
          - validate
      - name: DatasetInfo
        children: separate
  - title: Functional API
    package: behaverse
    contents:
      - list_datasets
      - download_dataset
      - load_dataset
      - get_dataset_info
      - validate_dataset
